name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2

    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18.0
        stable: true

    - name: Build
      run: make build

    - name: Run linter
      run: make lint

    - name: Start test environment
      run: make link-existing-docker-compose && make start-docker-environment

    - name: Run tests
      run: make test

    - name: Stop test environment
      run: make stop-docker-environment